on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: cams7-tests/hello-world-composite-action@v1
        with:
          who-to-greet: 'César A. Magalhães'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
